[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }
anyhow = "1.0"
chrono = "0.4.41"
cli_core = { path = "../core" }
