[package]
name = "cli_core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
walkdir = "2"
urlencoding = "2"
regex = "1.11"
open = "5.1.0"
once_cell = "1.21.3"
tokio = { version = "1.47.1", features = ["full"] }
